apiVersion: batch/v1
kind: Job

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}
{{- if .Values.hook.type }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.hook.type | quote }}
{{- if .Values.hook.deletePolicy }}
    argocd.argoproj.io/hook-delete-policy: {{ .Values.hook.deletePolicy | quote }}
{{- end }}
{{- end }}

spec:
  backoffLimit: {{ .Values.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}

  template:
    metadata:
      labels:
        app: {{ .Values.workload.name }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}

{{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default .Values.workload.name .Values.serviceAccount.name }}
{{- else if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- end }}

{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}

{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}

{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
{{- end }}

{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
{{- end }}

{{- if .Values.extraVolumes }}
      volumes:
{{ toYaml .Values.extraVolumes | nindent 8 }}
{{- end }}

      containers:
        - name: {{ .Values.workload.name }}
          image: "{{ .Values.workload.image.repository }}:{{ .Values.workload.image.tag }}"
          imagePullPolicy: {{ .Values.workload.image.pullPolicy }}

{{- if .Values.workload.command }}
          command:
{{ toYaml .Values.workload.command | nindent 12 }}
{{- end }}

{{- if .Values.workload.args }}
          args:
{{ toYaml .Values.workload.args | nindent 12 }}
{{- end }}

{{- if or .Values.secret.enabled .Values.configMap.enabled }}
          envFrom:
{{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ .Values.workload.name }}
{{- end }}
{{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ .Values.workload.name }}
{{- end }}
{{- end }}

{{- if .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml .Values.extraVolumeMounts | nindent 12 }}
{{- end }}

{{- if .Values.workload.resources }}
          resources:
{{ toYaml .Values.workload.resources | nindent 12 }}
{{- end }}