apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-secret
  namespace: stock-alert
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: platform-secret-store
    kind: SecretStore

  target:
    name: platform-secret

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: platform-bootstrap
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: platform-bootstrap
        property: POSTGRES_PASSWORD