apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: platform-secret
  namespace: stock-alert

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: platform-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: stock-alert/postgres
        property: username

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: stock-alert/postgres
        property: password