namespace: default

workload:
  name: app

  replicas: 1

  revisionHistoryLimit: 3

  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

  command: []

  args: []

  resources: {}

  service:
    enabled: true

    type: ClusterIP

    ports:
      - name: http
        port: 80
        targetPort: 80


ingress:
  enabled: false

  host: ""

  annotations: {}

  tls: []


configMap:
  enabled: false

  data: []


secret:
  enabled: false

  data: []


serviceAccount:
  enabled: false


securityContext:
  enabled: false

  spec: {}


initContainers: []


probes:
  enabled: false

  startupProbe: {}

  readinessProbe: {}

  livenessProbe: {}


imagePullSecrets: []


extraVolumes: []


extraVolumeMounts: []


nodeSelector: {}


affinity: {}


tolerations: []