namespace: default

workload:

  name: postgres

  replicas: 1

  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent

  containerPort: 5432

  resources: {}

persistence:

  enabled: true

  size: 20Gi

  storageClass: standard

  mountPath: /var/lib/postgresql/data


service:
  type: ClusterIP


secret:
  enabled: true
  data:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres

configMap:
  enabled: false
  data: []

securityContext:
  enabled: false

persistence:
  enabled: false

ingress:
  enabled: false
  className: nginx
  host: ""
  servicePort: 80
  annotations: {}

probes:
  enabled: false

  startup:
    enabled: false

  readiness:
    enabled: false

  liveness:
    enabled: false