{{- if .Values.workload.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

spec:
  ingressClassName: nginx

  rules:
  - host: {{ .Values.workload.ingress.host }}

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: {{ .Values.workload.name }}

            port:
              number: {{ .Values.workload.service.ports | first | dig "port" }}

{{- end }}