{{- if .Values.ingress.enabled }}

{{- $root := . }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | nindent 4 }}
{{- end }}

spec:
  ingressClassName: nginx

  rules:
  - host: {{ .Values.ingress.host }}

    http:
      paths:

{{- if .Values.ingress.paths }}

{{- range .Values.ingress.paths }}

      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}

        backend:
          service:
            name: {{ .serviceName | default $root.Values.workload.name }}
            port:
              number: {{ .servicePort | default $root.Values.ingress.servicePort }}

{{- end }}

{{- else }}

      - path: /
        pathType: Prefix

        backend:
          service:
            name: {{ .Values.workload.name }}
            port:
              number: {{ .Values.ingress.servicePort }}

{{- end }}

{{- end }}