{{- if .Values.workload.persistence.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.workload.name }}-pvc
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.workload.persistence.size }}

{{- if .Values.workload.persistence.storageClass }}

  storageClassName: {{ .Values.workload.persistence.storageClass }}

{{- end }}

{{- end }}