{{- if .Values.secret.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
{{- range .Values.secret.data }}
  {{ .name }}: {{ .value | quote }}
{{- end }}

{{- end }}