{{- if or .Values.secret.enabled (include "platform.secret.enabled" .) }}

###############################################################################
# Platform Secret
###############################################################################

{{- if (include "platform.secret.enabled" .) }}
apiVersion: v1
kind: Secret

metadata:
  name: platform-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
{{ include "platform.secret.data" . | indent 2 }}
---
{{- end }}

###############################################################################
# Application Secret
###############################################################################

{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
{{- range .Values.secret.data }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}

{{- end }}