{{- if .Values.workload.service.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.workload.service.type }}

  selector:
    app: {{ .Values.workload.name }}

  ports:
  - port: {{ .Values.workload.service.port }}
    targetPort: {{ .Values.workload.containerPort }}

{{- end }}