{{- if .Values.workload.service.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

spec:

  type: {{ .Values.workload.service.type }}

  selector:
    app: {{ .Values.workload.name }}

  ports:

{{- range .Values.workload.service.ports }}

  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}

{{- end }}

{{- end }}