{{- if .Values.configMap.enabled }}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

data:

{{- range .Values.configMap.data }}
  {{ .name }}: {{ .value | quote }}
{{- end }}

{{- end }}