apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.workload.name }}

  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
      name: tcp