apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.workload.name }}

  ports:

{{- if .Values.service.ports }}
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
{{- else }}
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.workload.containerPort }}
{{- end }}