apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rakeshh1990/my-gitops.git

    targetRevision: main

    path: charts/platform-stateful

    helm:
      valueFiles:
      - ../../values/platform/postgres.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true