apiVersion: v2
name: collector
description: OpenTelemetry Collector
type: application
version: 0.1.0

dependencies:
  - name: opentelemetry-collector
    version: 0.130.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts