apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-agent
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/rakeshh1990/my-gitops.git
    targetRevision: main
    path: helm
    helm:
      releaseName: ai-assistant
      values: |
        ollama:
          model: qwen2.5-coder:7b
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-assistant
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
