apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rakeshh1990/my-gitops.git
    targetRevision: main
    path: charts/observability/grafana

    helm:
      valueFiles:
        - ../../../values/platform/observability/grafana.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true