apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ai-agent-ollama
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/rakeshh1990/my-gitops.git

    targetRevision: main

    path: charts/platform-workload

    helm:
      valueFiles:
      - ../../values/ai-agent-ollama.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agent

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true